### ISSUE TITLE
baseline

### ISSUE THREAD

**Issue by ACMMM2024anonymous** [SSTC-Challenge/sstc-challenge.github.io#1]
开不开了

**Comment by SSTC-Challenge** [comment]
Dear Participant,

On behalf of the competition organizing committee, I would like to extend our sincerest apologies for the issues with the competition dataset.

We have identified some issues with certain datasets, causing inconvenience and delays. We deeply regret any inconvenience this may have caused you. We have decided to re-upload the datasets and make necessary adjustments.

We are working diligently to resolve this matter and anticipate completing the re-upload within 1 or 2 days. Once the datasets are ready, we will notify you immediately. We understand that this delay may disrupt your plans, and we will do our utmost to expedite the process while ensuring accuracy.

Once again, I apologize on behalf of the entire organizing committee. We greatly appreciate your patience and understanding. If you have any questions or need further assistance, please feel free to contact us.

Best regards,

The SSTC 2024 Challenge organizers
